apiVersion: v1
kind: Service
metadata:
  name: vr-match-api
spec:
  selector:
    app: vr-match-api
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      name: http
